[workspace]
resolver = "2"
members = [".", "examples/esp32-c3-example", "tools/xbox-controller-inspector"]
default-members = [".", "tools/xbox-controller-inspector"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.96.0"
repository = "https://github.com/wallem89/esp-xbox-controller-rs"

[package]
name = "xbox-controller-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

description = "no_std parser for Xbox Series controller BLE input reports"
homepage = "https://github.com/wallem89/esp-xbox-controller-rs"
documentation = "https://docs.rs/xbox-controller-core"
readme = "README.md"


keywords = ["xbox", "gamepad", "hid", "ble", "no-std"]
categories = ["embedded", "no-std", "parser-implementations"]

include = [
    "src/**",
    "CHANGELOG.md",
    "LICENSE-APACHE",
    "LICENSE-MIT",
    "README.md",
]

[features]
default = []

[dependencies]

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
